### ISSUE TITLE
✍️ Ergänzungswunsch - Dep. Anglistik / Amerikanistik und Romanistik

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-orga-breadcrumb#20]
Unter „Philosophische Fakultät“ fehlt das Department für Anglistik/Amerikanistik und Romanistik. 

(Kundin nach zufügen informieren: 🎫 http://go.fau.de/9r99- )

**Comment by xwolfde** [comment]
fixed
