### ISSUE TITLE
FAU-Link doppelt sich / Kritik

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-orga-breadcrumb#28]
Aus  http://go.fau.de/9s-22 🎫

Direkt unterhalb des dünneren Balken ganz oben mit dem FAU Logo ist nun sichtbar:
  Friedrich-Alexander ... / Technische Fakultät / Department Informatik (s. Dok1.pdf)

Das Logo links ober führt schon zu fau.de

**Comment by xwolfde** [comment]
Webauftritt muss richtig zugeordnet sein, dann funktioniert auch alles wie gewollt. Deswegen gibt es auch eine Warnmeldung im Backend
