### ISSUE TITLE
Neuer Eintrag Lehrstuhl für Schulpädagogik mit dem Schwerpunkt Digitalisierung im Unterricht

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/fau-orga-breadcrumb#34]
Institut für Erziehungswissenschaft > Lehrstuhl für Schulpädagogik mit dem Schwerpunkt Digitalisierung im Unterricht

🎫 - http://go.fau.de/9s44l

**Comment by xwolfde** [comment]
Das ist so wie es ist korrekt: Bei der Phil geht es nur bis Ebene der Departments. Die Institute sollen nicht auch nicht aufgenommen werden im Pfad. Daher ist hier das oberliegende Department zu wählen.
